### ISSUE TITLE
webexteamssdk.exceptions.ApiError: [404] Not Found - Unable to get message. [Tracking ID: ROUTER_62713947-AFC2-01BB-1903-0AFE1B641903]

### ISSUE THREAD

**Issue by fayazsk25** [WebexCommunity/WebexPythonSDK#174]
From last, i am unable to use the webexteamssdk. Can someone help me with this 

10:16:44 DEBUG    urllib3.connectionpool    https://webexapis.com:443 "GET /v1/messages/a8d66170-cbbb-11ec-9700-c51bbd345fr2 HTTP/1.1" 404 141
10:16:44 ERROR    asyncio                   Future exception was never retrieved
future: <Future finished exception=<ApiError [404] Not Found>>
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/fayaz/python_project/python_project_venv/errbot-root/plugins/err-backend-cisco-webex-teams/CiscoWebexTeams.py", line 440, in process_websocket
    spark_message = self.webex_teams_api.messages.get(activity['id'])
  File "/home/fayaz/python_project/python_project_venv/lib64/python3.6/site-packages/webexteamssdk/api/messages.py", line 321, in get
    json_data = self._session.get(API_ENDPOINT + '/' + messageId)
  File "/home/fayaz/python_project/python_project_venv/lib64/python3.6/site-packages/webexteamssdk/restsession.py", line 380, in get
    response = self.request("GET", url, erc, params=params, **kwargs)
  File "/home/fayaz/python_project/python_project_venv/lib64/python3.6/site-packages/webexteamssdk/restsession.py", line 345, in request
    check_response_code(response, erc)
  File "/home/fayaz/python_project/python_project_venv/lib64/python3.6/site-packages/webexteamssdk/utils.py", line 222, in check_response_code
    raise ApiError(response)
webexteamssdk.exceptions.ApiError: [404] Not Found - Unable to get message. [Tracking ID: ROUTER_62713947-AFC2-01BB-1903-0AFE1B641903]

**Comment by JoshuaStephen** [comment]
Hi @fayazsk25 

I am also facing the same issue while communicating with the bot using **WebSocket**.  I got the fix, where converting the message-id from **UUID** to **base64** format

I referred to the below link and applied the solution. please check this out

https://github.com/fbradyirl/webex_bot/blob/7df3778fc114f842f4ce6f28e04197a79e2b4347/webex_bot/websockets/webex_websocket_client.py#L78

**Comment by cmlccie** [comment]
Closing issue; `webexteamssdk`, today, does not support websockets.
